name: demo-serverless-cd-ondemand-workflow

concurrency: 
  group: default 
  #cancel-in-progress: true #cancel any currently running job or workflow in the same concurrency group.

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        type: string
        default: 'warning'

jobs:
  HelloLambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - run: zip -j HelloUdeALambda.zip ./HelloUdeALambda/index.js

      - run: aws lambda update-function-code --function-name=LambdaUdeA --zip-file=fileb://HelloUdeALambda.zip